package management.community.xiaonong.mapper;

import management.community.xiaonong.dto.IdToNameDTO;
import management.community.xiaonong.dto.TopicMgtDTO;
import management.community.xiaonong.model.Question;

import java.util.List;

public interface QuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Wed Mar 25 17:01:12 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Wed Mar 25 17:01:12 CST 2020
     */
    int insert(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Wed Mar 25 17:01:12 CST 2020
     */
    int insertSelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Wed Mar 25 17:01:12 CST 2020
     */
    Question selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Wed Mar 25 17:01:12 CST 2020
     */
    int updateByPrimaryKeySelective(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Wed Mar 25 17:01:12 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(Question record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated Wed Mar 25 17:01:12 CST 2020
     */
    int updateByPrimaryKey(Question record);

    //查询所有话题
    List<TopicMgtDTO> selectAllTopic(int offset,int size);

    //话题总数
    Integer selectTopicCount();

    //question里的creator转换成user的name
    List<IdToNameDTO> selectTandU();

    //根据id查询话题
    TopicMgtDTO selectById(Long id);

    //根据title关键词查找话题
    List<TopicMgtDTO> selectByTitle(String topictitle);
}